version: '3'
services:
    oracle:
        container_name: oracledb
        build: ./docker/oracle
        shm_size: 4096M
        volumes:
            - "./.docker-volumes/oracledb:/u01/app/oracle/oradata" # persistent oracle database data.
            - "./docker/oracle/startup_scripts:/u01/app/oracle/scripts/startup"
        ports:
            - 1521:1521
            - 8080:8080
        environment:
            - ORACLE_ALLOW_REMOTE=true
            - ORACLE_PWD=PWD