CREATE USER <YOUR_DB_NAME_HERE> IDENTIFIED BY <YOUR_DB_PASSWORD_HERE>;
GRANT CONNECT, RESOURCE, DBA TO <YOUR_DB_NAME_HERE>;
GRANT UNLIMITED TABLESPACE TO <YOUR_DB_NAME_HERE>;

ALTER SYSTEM SET disk_asynch_io = FALSE SCOPE = SPFILE;

